import { BrowserRouter, Route, Routes } from "react-router-dom";
import { CustomMessage } from "./Helpers";
import { Layout } from "./Layout";

export function App() {
  return (
    <BrowserRouter basename="/agile-talent-solutions/">
      <Routes>
        <Route path="/" element={<Layout />}>
          <Route index element={<>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ullam hic eveniet consequatur rem necessitatibus vel quaerat sed itaque accusantium quibusdam aspernatur, doloribus tenetur officiis? Architecto reprehenderit omnis sit animi esse.
            Fugit, natus aspernatur fuga dolores molestiae molestias. Inventore dolores fuga perspiciatis provident error incidunt quae molestias minus! Exercitationem fugit assumenda quas beatae doloribus, accusamus vitae explicabo alias? Nam, molestias quaerat?
            Neque, impedit consequatur praesentium ipsum corrupti aliquam vitae sit explicabo maiores quaerat odio animi id, saepe cupiditate porro iusto quidem commodi necessitatibus nobis deleniti ut vel voluptatum, beatae vero! Repudiandae?
            Pariatur accusantium sint deleniti culpa veritatis iure veniam nemo, distinctio harum! Quibusdam possimus doloribus unde modi quaerat tenetur incidunt dicta omnis! Inventore perferendis odio voluptatem nisi, asperiores quaerat eveniet praesentium.
            Distinctio, dignissimos veniam. Nobis libero ex distinctio reiciendis quasi? Ullam tempora dolore consequatur? Atque quaerat, perferendis, ratione earum nam libero cumque natus aliquam et ad iusto assumenda, ab veritatis culpa.
            Nam ex ut dolore tempore praesentium? Voluptatum ipsum, alias inventore itaque officia, ullam hic tempore aliquam reprehenderit suscipit vitae neque commodi ut consectetur ducimus quae provident mollitia. Voluptas, quis possimus.
            Quod vitae id amet quaerat aliquam fuga sed labore dicta autem est distinctio, ut nulla! Accusantium, laudantium, quasi incidunt voluptatem eius porro molestiae excepturi adipisci distinctio ducimus alias minima! Aspernatur!
            Officia, veritatis. Adipisci autem nisi repellat nesciunt sequi beatae asperiores aut quo doloremque molestias error aliquam doloribus nam, rerum voluptate officia modi at animi architecto expedita numquam fuga voluptatibus quod?
            Odit, velit, aliquid ea quisquam ipsa dolor illo provident eaque ipsum laudantium minus error nemo reiciendis adipisci beatae. Ab corrupti blanditiis laborum quasi odio at soluta harum, inventore maiores. Tempora.
            Corporis ex reprehenderit maiores repellendus vitae repudiandae fuga. Optio assumenda quas eveniet vero error. Suscipit ullam dolore, est temporibus possimus, enim vero tempora deserunt facilis consequatur voluptatibus error ex unde.
            Nihil modi rerum illum ipsam adipisci eius itaque vero odit ipsa quia aperiam nulla ipsum voluptatem ducimus pariatur nam, illo a, minima quos ab aliquam repellendus incidunt aut laborum. Assumenda.
            Aliquid et iure, tenetur accusantium porro architecto ullam fugit velit neque ea soluta facere aut eaque repudiandae, libero officia natus quibusdam aspernatur voluptatibus error. Debitis voluptatibus optio ipsa aut ullam.
            Earum dolores modi ipsum doloremque tempora doloribus ab exercitationem maiores, aut architecto assumenda ex eligendi alias fuga quis veniam? Expedita odit, cupiditate omnis animi quo maiores fugiat! Aperiam, minima corporis.
            Aliquid recusandae voluptatibus nihil. Error, omnis? Quos, eos illo perspiciatis in soluta repellendus modi perferendis incidunt pariatur sed facilis ipsam! Veritatis a, pariatur libero consequatur sed ratione consequuntur harum debitis?
            Eveniet dignissimos, obcaecati reiciendis minima iste cumque praesentium possimus corporis est magnam dolor vitae iure ab qui quis commodi? Quas iusto corporis architecto laborum modi nostrum, possimus minus sunt nam?
            Possimus inventore doloribus totam officiis perferendis aliquid repellendus molestiae, reiciendis vitae repudiandae provident natus nesciunt ducimus pariatur eligendi tempora fugiat. Ratione animi vero repellat libero aspernatur deleniti maxime ipsa laborum.
            A repellat sunt ea veritatis facilis eos! Quod, modi? Corrupti ab dignissimos excepturi natus! Tempora officia iste earum minus, vitae provident dolor nulla pariatur odit quis deleniti distinctio doloremque reprehenderit?
            Veritatis totam, a minus accusantium aliquam doloremque minima itaque consequuntur impedit illo dignissimos, at pariatur maxime, reiciendis voluptates labore numquam earum nemo ipsum temporibus qui. Quasi nostrum quidem natus facilis.
            Atque tempore, laudantium quaerat natus explicabo delectus aperiam adipisci optio deserunt ipsum, porro esse? Sequi earum animi incidunt voluptatibus unde voluptas amet suscipit est aliquam? Architecto illo excepturi consequatur reiciendis.
            Veritatis voluptatum, unde necessitatibus nemo ullam natus in, nihil culpa placeat omnis nobis, fugit officiis facilis nulla recusandae veniam! Eius quos recusandae necessitatibus ex qui porro, hic deleniti? Deserunt, itaque.
            Itaque eveniet numquam reprehenderit sint quisquam sapiente. Expedita aliquid deleniti nam ullam, eos corrupti vitae autem et repellat fugit cum minus id dolorem libero ex aperiam facere. Quibusdam, aut nesciunt?
            Quibusdam doloribus ipsa nemo modi laudantium ullam quidem, sit voluptatibus debitis at incidunt voluptatem placeat quae maiores quasi dolor dicta labore, cupiditate commodi nam. Quam, libero nesciunt. Quibusdam, odit enim.
            Magnam necessitatibus et cupiditate, atque quas deleniti ipsa magni ea fugiat quo asperiores expedita quam eos obcaecati, quasi vel! Reiciendis nisi debitis nemo ut. Et nam explicabo eos repellendus voluptatem!
            Et, animi quos necessitatibus ullam similique rerum cum iste atque optio incidunt, expedita doloribus voluptatem dignissimos aliquid. Reiciendis iusto ipsa commodi quis expedita, maiores necessitatibus, reprehenderit rerum aperiam perferendis consequuntur.
            Labore dolorem odio, ad maiores tempora perspiciatis enim voluptates sequi! Iure soluta fuga autem quam velit eveniet atque sed quia eaque molestiae! Est architecto qui ut laboriosam nemo? Amet, aut?
            Repellendus, suscipit cupiditate esse impedit ab enim, expedita inventore animi hic dolorum debitis repellat? Quod ut voluptatibus quasi aut expedita? Minima iure eum totam sint quae reiciendis debitis incidunt quisquam?
            Dolorum, laudantium fuga cumque, facere quis, dolores architecto sequi vitae tempore dolorem autem aut eligendi sed rem totam molestiae maiores id praesentium. Quam adipisci optio, aliquid fuga sed architecto cum?
            Repellendus ad enim, earum dolores mollitia facere quos voluptatibus dolor? Nemo, cupiditate reiciendis debitis aut repellendus magnam ducimus tempore, quam at aliquid similique! Quaerat ducimus eos velit saepe amet omnis.
            Minima, quae molestias? Facilis minima quod voluptas. Harum, fugiat tempora rem repellat odio, ut voluptatem est sapiente magnam ullam facere possimus ipsa quae asperiores voluptate soluta. Tenetur nobis quis veniam?
            Distinctio laborum tempore esse amet explicabo obcaecati nisi eos repellendus nostrum. Sunt, consectetur et sapiente blanditiis repellendus reprehenderit officia, perferendis voluptatibus unde aliquam dignissimos alias voluptates aspernatur exercitationem, minima quo.
            Voluptatem similique reprehenderit, a voluptate ipsum eveniet commodi nesciunt expedita corrupti nulla, inventore ea dolor quisquam id aliquid placeat iusto iure perspiciatis ex aut ipsam totam exercitationem. Sapiente, nesciunt commodi.
            Error nobis ea veritatis nemo libero est, nesciunt pariatur magni earum dicta, ratione optio! Itaque rerum non exercitationem earum ab, saepe suscipit praesentium voluptas iusto omnis tempora neque vel qui.
            Dolorum aliquid, nemo possimus sunt in quod laudantium sequi alias magni molestias beatae dolores dolore aperiam est nisi rem voluptate enim accusantium. Deserunt cum eos nisi perferendis odio quibusdam delectus.
            Nostrum rerum, vel laboriosam, magnam recusandae soluta vero inventore quia velit reprehenderit est, aspernatur suscipit animi commodi nemo natus perspiciatis perferendis quidem temporibus enim neque et nisi? Commodi, quod repellendus.
            Perspiciatis voluptates iusto dolore vero molestiae, laborum necessitatibus at dicta, illum velit eius corporis voluptatum dignissimos sequi incidunt dolor architecto eos itaque, facere aperiam? Maxime quos autem illo consequuntur quod.
            Ipsam voluptatem, libero sit earum quae consequatur adipisci eligendi error numquam hic placeat delectus architecto at voluptates, modi molestias voluptatibus? Vitae asperiores quam, maiores aut debitis quo. Sequi, adipisci voluptatum!
            Ullam, facere blanditiis tenetur voluptates id rem veniam eligendi eum recusandae adipisci error atque veritatis optio modi eveniet earum vel ratione aliquam, quasi suscipit voluptatibus qui accusantium doloribus magnam. Consectetur.
            Dolore eum ut dolor vel commodi eveniet quasi tenetur. Eos ad tempore nemo consequuntur, totam ipsum odit quia accusamus quidem magnam maxime nulla soluta ab deserunt possimus expedita harum aperiam!
            Saepe vel obcaecati, ea voluptatibus in reiciendis fuga exercitationem officiis libero dolores assumenda laborum quos facere, accusamus enim officia quam. Ullam sit necessitatibus quibusdam illo numquam corrupti suscipit, optio sunt?
            Accusantium, officia eius blanditiis odio dolore ratione quidem! Minus id ex reiciendis earum aliquid quis, sit, quam facilis itaque tempore voluptatem sint aperiam maiores ducimus quo officiis laborum iusto perferendis.
            Architecto temporibus modi repudiandae tempora, ea maiores mollitia. Odit, atque beatae ratione veniam magnam ullam vitae laudantium iusto expedita alias, odio labore eligendi quos reiciendis. Dicta autem libero beatae ad?
            Sint, nulla voluptates nemo possimus esse non. Fugit sit impedit pariatur obcaecati, cupiditate, nihil optio voluptate accusamus dolorem error magni quo itaque ipsum deserunt. Explicabo a aliquam corrupti esse doloremque?
            Sed, placeat! Beatae, non magnam. Blanditiis voluptatem dolorem, aut iusto quod totam, veniam nostrum dolor id rem enim unde numquam corrupti, consectetur consequatur pariatur eos! Quis dolores autem aut sunt?
            Quasi vitae, numquam consequuntur enim corporis, repellendus sed placeat error impedit natus tempore laudantium delectus eum commodi saepe consequatur ullam animi ex exercitationem. Distinctio excepturi quia esse, doloribus corporis voluptas.
            At, optio voluptatem repudiandae possimus eum perferendis consectetur molestiae minima commodi doloremque expedita quod et, asperiores reprehenderit officia ipsam ratione repellendus deserunt. Illo eveniet, similique iure magnam quo numquam eum.
            Iure, sit omnis facilis quis magnam nostrum, minima dolores odio quidem mollitia aliquid quisquam architecto ducimus beatae quas labore cum totam maxime debitis assumenda dolorem, ut at autem consectetur? Consequatur!
            Velit fugit aperiam at, ducimus et, voluptates sint aliquam ipsum rem quam hic necessitatibus natus eligendi, odio alias? Dolorum quod quo distinctio nisi neque ipsa expedita dolorem sed fuga similique.
            Aliquam, excepturi, quibusdam quisquam modi eius commodi quod id illo corrupti vel corporis nulla soluta rem ab necessitatibus! Soluta omnis iure iste nobis nesciunt explicabo rerum sint unde ipsum eligendi.
            Ab atque exercitationem enim ipsum iste! A neque porro, totam nisi consequuntur delectus in itaque nesciunt accusamus ut soluta sapiente esse quaerat aut officiis obcaecati quo eius cupiditate, quia nihil.
            Facilis, voluptates atque quo quae voluptate cupiditate omnis dolorum debitis placeat quas laborum, perferendis ex repudiandae ipsum beatae, nam molestiae tempora nesciunt aspernatur obcaecati optio provident cumque corrupti. Dolorem, ullam!
            Soluta, rerum molestiae quos, animi culpa cum voluptas ipsa, sapiente tenetur doloribus sequi sed qui quis ad ullam aut ipsam nesciunt natus? Animi voluptatem deleniti vel nam rerum, provident doloribus?
            Voluptatem, delectus sequi corporis in repellendus beatae provident tempora voluptates magnam perspiciatis ducimus vel facilis. Libero praesentium sapiente, inventore iusto, exercitationem corporis aliquam facilis deleniti quaerat molestiae nisi amet quod?
            Totam vero recusandae voluptates consequuntur blanditiis quos quibusdam delectus quo. Quibusdam vel provident iusto commodi nam aliquid tenetur, assumenda quisquam inventore eligendi quod rem amet nemo corrupti repellat esse neque.
            Natus unde nulla error officia, corrupti labore voluptatibus totam quo nobis ad aliquam dolorem voluptates a maiores in, velit quas. Expedita debitis veniam dolor placeat similique eaque, perspiciatis ut laboriosam.
            Natus nihil fuga placeat repudiandae maiores molestias, officia rerum quam, similique quis perferendis ut quidem ipsum, ab delectus. Corrupti accusantium quas illo eligendi recusandae, minus repellat facilis molestias culpa voluptatibus.
            Quod libero aspernatur, beatae explicabo, deserunt quia laudantium voluptate neque doloribus sint ratione doloremque magni perferendis consequuntur rem eveniet? Sit, vel. Quos, doloribus illo corrupti quibusdam quo molestiae a dolore?
            Omnis, repellat. Hic quaerat officia, soluta corporis ullam dolorem doloribus eos libero sed aspernatur aut perspiciatis delectus, minima labore ipsa? Eligendi optio itaque nemo maiores libero consequatur debitis rerum eius?
            Consequatur praesentium maiores possimus, sed beatae corrupti nemo voluptatum, odit, voluptas ea quasi tempora distinctio in. Veritatis cupiditate minus dicta aliquid. Ipsam fugiat rerum iusto fuga optio velit minus voluptatum?
            Pariatur corrupti dolorem obcaecati ab ad molestias architecto. Nisi ut necessitatibus cupiditate tempora, maiores est tempore. Similique, ut ratione nulla quaerat dicta cum corrupti voluptatum, nostrum a, natus omnis reiciendis.
            Sit dolorum debitis quidem explicabo velit, reiciendis quisquam, accusamus quia quo et autem, ad est qui! Sit, magnam facere eligendi eos possimus necessitatibus accusamus soluta dolores ipsa impedit voluptatum laborum!
            Laudantium necessitatibus eius impedit tenetur error dolor aspernatur excepturi, magnam facere recusandae vitae illo doloribus ipsam reiciendis! Maxime perferendis eius quidem ullam autem magni distinctio id blanditiis, quo quas perspiciatis.
            Eos iure cupiditate blanditiis ratione illo ut excepturi nam laborum, minus voluptas aut ipsa deserunt harum repudiandae animi porro placeat. Animi tenetur nesciunt aut veniam id. Veritatis inventore commodi omnis.
            Ea, quis magni quisquam mollitia, quos ratione sit illum a dolorem placeat laborum nemo, tempore facilis. Dolorem, iste labore? Ducimus nisi ullam nulla necessitatibus id dolor voluptate ut repellendus explicabo.
            Sit recusandae nisi temporibus optio neque commodi dolorem fuga? Doloremque possimus quia quidem aut a magnam ut, delectus necessitatibus vitae reiciendis officiis eaque quod nam perferendis eveniet distinctio nemo aliquam?
            Alias labore qui officiis quia delectus soluta iusto, quidem dolores ratione facilis similique libero fuga temporibus consequuntur nemo ipsum magnam at? Architecto, veritatis nisi illum sunt ex modi sed nulla.
            Laboriosam iste possimus distinctio, consectetur ea, harum facere saepe sint eligendi ipsa doloribus pariatur modi culpa assumenda. Doloremque modi quae quaerat laboriosam sequi ullam aliquam laborum adipisci, ut, dolore neque.
            Voluptatum, nesciunt dolorum necessitatibus dignissimos fugit molestiae velit aperiam alias minima a expedita temporibus incidunt repudiandae vero recusandae sint iusto, eaque ex ut accusamus? Aliquid, consequatur officiis? Excepturi, laboriosam cupiditate.
            Tempora odit cupiditate nisi corrupti aperiam nostrum possimus veritatis quia soluta dolore. Deleniti iste qui itaque numquam eveniet quisquam, aliquid unde. Quisquam eum eos accusamus quasi temporibus nam fuga officiis!
            Ea aperiam repellat enim soluta nisi dolores excepturi iure ipsum voluptatem harum voluptate beatae, tenetur tempore veniam dignissimos aut distinctio vero hic quisquam quasi sequi, tempora, eveniet sunt! Quos, culpa!
            Ullam a atque tempore, ex, quidem dolores suscipit esse molestiae alias aliquid amet eaque deserunt nemo totam non. Laborum cupiditate animi temporibus fuga odit amet voluptatem eaque debitis nihil repellendus.
            Quo inventore ducimus dolore sit accusamus assumenda, ullam id et, quam repellat vel sed adipisci pariatur eveniet non quidem eum vero necessitatibus voluptatum quia. Delectus optio voluptatibus voluptas tempore earum!
            Voluptate repellat illum qui, molestiae molestias libero? Alias facilis nulla tenetur, placeat eaque unde soluta minima maxime inventore cum repellat animi corrupti perferendis ad recusandae autem aliquam iure fuga nemo.
            Atque iste incidunt fugiat dolor impedit? Sequi quaerat, omnis, in rem eaque deleniti perspiciatis nulla natus, sunt laborum dolorum? Praesentium, perferendis? Nisi sunt nemo repellat temporibus explicabo soluta amet optio.
            Optio voluptas unde velit alias totam magnam libero debitis consectetur ex qui esse et cupiditate, nisi voluptatem molestias, ipsa, eius dicta? Mollitia optio expedita suscipit in quos voluptatibus provident impedit?
            Nesciunt, et ea pariatur nostrum impedit unde veniam non quibusdam amet sed, cumque saepe. Adipisci accusantium illo beatae placeat aperiam recusandae. Exercitationem, adipisci doloremque beatae repudiandae nostrum ut ad neque.
            Vel ipsum ullam veniam laudantium a corrupti sit culpa perferendis soluta fugiat magni ratione aliquid quibusdam eaque officiis autem quisquam quis totam atque exercitationem, nostrum fuga! Amet magnam laudantium error?
            Tenetur veritatis possimus at velit iure eveniet incidunt distinctio, tempore officia harum inventore deleniti eum autem fugiat odio dolor numquam rem hic quos minima. Neque incidunt perferendis laborum aperiam perspiciatis?
            Mollitia minus deleniti magni repellat reprehenderit rerum numquam vero unde, cum vitae deserunt nesciunt ullam quasi obcaecati totam dignissimos a quia rem tenetur. Alias voluptates tempore dicta ipsa odit sed!
            Voluptates libero nihil, laboriosam quae ducimus, cupiditate explicabo assumenda magnam quo eaque quibusdam alias consequuntur, sapiente unde? Reiciendis, optio beatae necessitatibus similique neque tenetur fuga alias corporis itaque perspiciatis molestiae!
            Tempore vel nesciunt labore nisi incidunt ad sint, repudiandae distinctio odit dolor. Quisquam nisi rerum distinctio placeat quos omnis! Id dicta repellendus doloremque recusandae, repellat distinctio quas repudiandae blanditiis? Quibusdam.
            Autem, minima vero illum ratione odit nisi eos similique saepe, excepturi numquam quas voluptas laudantium hic error minus quam. Accusamus magnam fugit voluptas voluptates illo quaerat ut expedita similique quibusdam.
            Expedita saepe commodi, quibusdam nam sunt amet. Nesciunt quia facilis tempora blanditiis, architecto doloremque voluptatem nobis consequuntur voluptatibus cumque unde est eaque atque maxime ab veniam fuga odio sint laboriosam.
            Omnis non consequatur sint repudiandae dignissimos, facere reprehenderit laboriosam delectus, maiores accusamus quia optio, praesentium eum? Voluptatem assumenda expedita repellendus? Quisquam nulla distinctio praesentium modi corrupti molestiae maiores. Amet, totam?
            Totam, nam. Modi animi debitis doloremque ratione et veniam illo ullam architecto, distinctio neque. Soluta quia nemo inventore reprehenderit architecto quis, laboriosam amet aspernatur ducimus quasi consequatur accusamus explicabo dolores!
            Facilis praesentium nemo veniam! Pariatur aspernatur eum harum ipsa consequuntur quaerat, temporibus, qui amet vel molestias sequi debitis excepturi sit ducimus, possimus dicta officiis laudantium exercitationem. Accusantium, esse. Nobis, vel.
            Facilis dolorem modi eaque consectetur facere earum impedit voluptatibus accusantium quia odit eum cum assumenda architecto, molestiae nisi corrupti ut quas beatae dolor excepturi necessitatibus reprehenderit perspiciatis, adipisci atque? Non.
            Ratione ad non sequi, perspiciatis praesentium esse cum pariatur aperiam temporibus libero neque provident alias ipsum, repudiandae aspernatur cupiditate recusandae eaque itaque corrupti dignissimos consequatur. Laudantium, facilis? Cumque, quidem quas!
            Molestias quam unde sequi necessitatibus expedita dolore dicta cumque voluptatum similique possimus quibusdam ex at numquam magnam non doloremque impedit, nobis earum asperiores quis hic. Distinctio amet iste sunt iusto.
            Ratione est perspiciatis voluptate at voluptates nulla soluta repellendus architecto eaque tempora similique ex nostrum, reiciendis sed voluptatum dolor fugit laboriosam quam magni cumque unde eum expedita aperiam illum? Iusto?
            Quos doloribus, sunt sed tempore recusandae praesentium architecto ab dolore dicta perspiciatis, ratione earum enim, deserunt ad. Minus aliquam, velit inventore quae saepe, a quas, harum sapiente quos hic quisquam.
            Consequuntur repudiandae nisi nemo, modi eum necessitatibus impedit vitae nostrum aliquid alias unde ipsa perferendis voluptatibus sit libero architecto explicabo nihil. Quibusdam quisquam nihil quia ex fuga vel nostrum modi!
            Numquam illo iusto sint, aut qui, atque, veritatis tempora est vero ipsa eaque tenetur id ullam mollitia ad amet. Tempore sunt quidem hic accusantium quasi dolor? Ipsam sapiente optio minima.
            Voluptates perspiciatis vel adipisci quo qui nostrum impedit quod ducimus commodi iure, mollitia, nobis, distinctio delectus veritatis molestias laboriosam harum sequi eos maxime odio doloremque modi voluptatibus fugiat? Suscipit, quidem.
            Earum corporis minus dolorum saepe, praesentium magnam amet recusandae error ut in quibusdam est, quisquam nobis ullam adipisci suscipit beatae exercitationem cupiditate. Nisi temporibus quam natus repellat provident sequi reprehenderit?
            At dicta vel illo deleniti perspiciatis cum, saepe commodi dignissimos tempora eius, eligendi esse exercitationem veniam explicabo, voluptates voluptatibus beatae. Autem tenetur voluptatibus ad. In error cupiditate nostrum qui quidem?
            Labore optio dolore neque nulla soluta! Dicta minima debitis quo, rem eius laborum aspernatur fuga similique exercitationem incidunt, alias est, accusantium modi dolor temporibus culpa beatae! Expedita aspernatur explicabo cumque?
            Architecto dolorum, suscipit dignissimos laboriosam fugiat fuga distinctio dolore optio natus amet? Magnam expedita quos rem alias facere nemo odio ipsum ut aliquam perspiciatis, nulla recusandae fugit. Velit, aut minus?
            Non minus ipsa obcaecati architecto, possimus iure ut pariatur, perferendis corporis tenetur mollitia sed at odio commodi quae earum corrupti incidunt hic maiores autem eos repellendus. Nulla odio vero cumque.
            Illum, incidunt ad. Vero, esse, ipsum beatae labore dolores explicabo corporis aperiam incidunt nobis velit obcaecati, dolorum cum similique quam ratione repellat hic amet mollitia modi exercitationem sed illum eligendi!
            Saepe illo vel sit nesciunt nisi adipisci cum rem deserunt eveniet tenetur optio aspernatur dolorum, quo tempora eius inventore et enim alias voluptatum quaerat. Quaerat minima nostrum repudiandae omnis fuga!</>} />
          <Route path="search" element={<></>} />
          <Route path="profile/:id" element={<></>} />
          <Route path="*" element={<CustomMessage message="404 page not found" />} />
        </Route>
      </Routes>
    </BrowserRouter>
  )
}